{   
    'data' : '/home/arg-dope/Deep-Object-Pose/dataset/wamv_10m', 
    'workers' : 1 ,
    'batchsize' : 5 ,
    'namefile' : 'wamv_10m' ,
    'gpuids' : [0] ,
    'outf' : 'wamv_10m' ,
    'epochs' : 10
}